# Site settings
title: Programming Languages, Systems, and Logic
email: psl@imada.sdu.dk
description: > # this means to ignore newlines until "baseurl:"
  Programming Languages, Systems, and Logic research group website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://psl.sdu.dk" # the base hostname & protocol for your site
permalink: /events/:year-:month-:day-:title
# Build settings
incremental: true
markdown: kramdown
exclude: [ "layout_archive", "utils" ]
excerpt_separator: "<!--more-->"
group_short: "PSL"
group_name: "Programming Languages, Systems, and Logic"
exclude: [ "no_publications" ]
incremental: false